# Generated by Django 4.1 on 2024-06-27 09:59

from django.conf import settings
from django.db import migrations, models

import logging

def forwards_func(apps, schema_editor):
    """
    Transfert data from director to directors (foreignKey to ManytoMany)
    """
    db_alias = schema_editor.connection.alias
    phd_model = apps.get_model("school", "phdstudent")

    for phd in phd_model.objects.using(db_alias).all():
        try:
            phd.directors.add(phd.director)
            phd.save()
        except Exception:
            pass


def backwards_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0014_models_defaultorder'),
    ]
    operations = [
        migrations.AddField(
            model_name='phdstudent',
            name='directors',
            field=models.ManyToManyField(blank=True, related_name='phd_student', to=settings.AUTH_USER_MODEL),
        ),

        migrations.RunPython(
            forwards_func, 
            backwards_func
        ),

        migrations.RemoveField(
            model_name='phdstudent',
            name='director',
        ),
        
        migrations.AlterField(
            model_name='phdstudent',
            name='thesis_object',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
